/* tslint:disable */
require("./PermissionCenter.module.css");
const styles = {
  persona: 'persona_a3aa5de5',
  permissionCenter: 'permissionCenter_a3aa5de5',
  container: 'container_a3aa5de5',
  row: 'row_a3aa5de5',
  column: 'column_a3aa5de5',
  titleContainer: 'titleContainer_a3aa5de5',
  title: 'title_a3aa5de5',
  refresh: 'refresh_a3aa5de5',
  tabContainer: 'tabContainer_a3aa5de5',
  tabItem: 'tabItem_a3aa5de5',
  tabActiveItem: 'tabActiveItem_a3aa5de5',
  tabContent: 'tabContent_a3aa5de5',
  userContainer: 'userContainer_a3aa5de5',
  allUserContainer: 'allUserContainer_a3aa5de5',
  userRowContainer: 'userRowContainer_a3aa5de5',
  userRow: 'userRow_a3aa5de5',
  user: 'user_a3aa5de5',
  userActive: 'userActive_a3aa5de5',
  userInvalid: 'userInvalid_a3aa5de5',
  placeholderItem: 'placeholderItem_a3aa5de5',
  load: 'load_a3aa5de5',
  groupHeader: 'groupHeader_a3aa5de5',
  iconContainer: 'iconContainer_a3aa5de5',
  icon: 'icon_a3aa5de5',
  iconInit: 'iconInit_a3aa5de5',
  iconTurned: 'iconTurned_a3aa5de5',
  groupTitleContainer: 'groupTitleContainer_a3aa5de5',
  groupTitle: 'groupTitle_a3aa5de5',
  groupSubTitle: 'groupSubTitle_a3aa5de5',
  groupTitleLinkOpen: 'groupTitleLinkOpen_a3aa5de5',
  groupTitleLinkPerm: 'groupTitleLinkPerm_a3aa5de5',
  permissions: 'permissions_a3aa5de5',
  permissionLevel: 'permissionLevel_a3aa5de5',
  cardAndUsersIcon: 'cardAndUsersIcon_a3aa5de5',
  editIcon: 'editIcon_a3aa5de5',
  editIconActive: 'editIconActive_a3aa5de5',
  editIconHidden: 'editIconHidden_a3aa5de5',
  groupCard: 'groupCard_a3aa5de5',
  groupCardContainer: 'groupCardContainer_a3aa5de5',
  groupCardButtonContainer: 'groupCardButtonContainer_a3aa5de5',
  dataContainer: 'dataContainer_a3aa5de5',
  dataRow: 'dataRow_a3aa5de5',
  dataKeyShort: 'dataKeyShort_a3aa5de5',
  dataKeyLong: 'dataKeyLong_a3aa5de5',
  dataValue: 'dataValue_a3aa5de5',
  userCard: 'userCard_a3aa5de5',
  userCardContainer: 'userCardContainer_a3aa5de5',
  userCardButtonContainer: 'userCardButtonContainer_a3aa5de5',
  nestedGroup: 'nestedGroup_a3aa5de5',
  type: 'type_a3aa5de5',
  name: 'name_a3aa5de5',
  spGroup: 'spGroup_a3aa5de5',
  spGroupInvalid: 'spGroupInvalid_a3aa5de5',
  otherAzureGroup: 'otherAzureGroup_a3aa5de5',
  otherAzureGroupInvalid: 'otherAzureGroupInvalid_a3aa5de5',
  m365Group: 'm365Group_a3aa5de5',
  m365GroupInvalid: 'm365GroupInvalid_a3aa5de5',
  branchContainer: 'branchContainer_a3aa5de5',
  tooltip: 'tooltip_a3aa5de5',
  modalColumn: 'modalColumn_a3aa5de5',
  headline: 'headline_a3aa5de5',
  successIcon: 'successIcon_a3aa5de5',
  errorIcon: 'errorIcon_a3aa5de5',
  openLink: 'openLink_a3aa5de5',
  modalCheckbox: 'modalCheckbox_a3aa5de5'
};

export default styles;
/* tslint:enable */