/* tslint:disable */
require("./PermissionCenter.module.css");
const styles = {
  persona: 'persona_e2b6ef4c',
  permissionCenter: 'permissionCenter_e2b6ef4c',
  container: 'container_e2b6ef4c',
  row: 'row_e2b6ef4c',
  column: 'column_e2b6ef4c',
  titleContainer: 'titleContainer_e2b6ef4c',
  title: 'title_e2b6ef4c',
  refresh: 'refresh_e2b6ef4c',
  tabContainer: 'tabContainer_e2b6ef4c',
  tabItem: 'tabItem_e2b6ef4c',
  tabActiveItem: 'tabActiveItem_e2b6ef4c',
  tabContent: 'tabContent_e2b6ef4c',
  userContainer: 'userContainer_e2b6ef4c',
  allUserContainer: 'allUserContainer_e2b6ef4c',
  userRowContainer: 'userRowContainer_e2b6ef4c',
  userRow: 'userRow_e2b6ef4c',
  user: 'user_e2b6ef4c',
  userActive: 'userActive_e2b6ef4c',
  userInvalid: 'userInvalid_e2b6ef4c',
  placeholderItem: 'placeholderItem_e2b6ef4c',
  load: 'load_e2b6ef4c',
  groupHeader: 'groupHeader_e2b6ef4c',
  iconContainer: 'iconContainer_e2b6ef4c',
  icon: 'icon_e2b6ef4c',
  iconInit: 'iconInit_e2b6ef4c',
  iconTurned: 'iconTurned_e2b6ef4c',
  groupTitleContainer: 'groupTitleContainer_e2b6ef4c',
  groupTitle: 'groupTitle_e2b6ef4c',
  groupSubTitle: 'groupSubTitle_e2b6ef4c',
  groupTitleLinkOpen: 'groupTitleLinkOpen_e2b6ef4c',
  groupTitleLinkPerm: 'groupTitleLinkPerm_e2b6ef4c',
  permissions: 'permissions_e2b6ef4c',
  permissionLevel: 'permissionLevel_e2b6ef4c',
  cardAndUsersIcon: 'cardAndUsersIcon_e2b6ef4c',
  editIcon: 'editIcon_e2b6ef4c',
  editIconActive: 'editIconActive_e2b6ef4c',
  editIconHidden: 'editIconHidden_e2b6ef4c',
  groupCard: 'groupCard_e2b6ef4c',
  groupCardContainer: 'groupCardContainer_e2b6ef4c',
  groupCardButtonContainer: 'groupCardButtonContainer_e2b6ef4c',
  dataContainer: 'dataContainer_e2b6ef4c',
  dataRow: 'dataRow_e2b6ef4c',
  dataKeyShort: 'dataKeyShort_e2b6ef4c',
  dataKeyLong: 'dataKeyLong_e2b6ef4c',
  dataValue: 'dataValue_e2b6ef4c',
  userCard: 'userCard_e2b6ef4c',
  userCardContainer: 'userCardContainer_e2b6ef4c',
  userCardButtonContainer: 'userCardButtonContainer_e2b6ef4c',
  nestedGroup: 'nestedGroup_e2b6ef4c',
  type: 'type_e2b6ef4c',
  name: 'name_e2b6ef4c',
  spGroup: 'spGroup_e2b6ef4c',
  spGroupInvalid: 'spGroupInvalid_e2b6ef4c',
  otherAzureGroup: 'otherAzureGroup_e2b6ef4c',
  otherAzureGroupInvalid: 'otherAzureGroupInvalid_e2b6ef4c',
  m365Group: 'm365Group_e2b6ef4c',
  m365GroupInvalid: 'm365GroupInvalid_e2b6ef4c',
  branchContainer: 'branchContainer_e2b6ef4c',
  tooltip: 'tooltip_e2b6ef4c',
  modalColumn: 'modalColumn_e2b6ef4c',
  headline: 'headline_e2b6ef4c',
  successIcon: 'successIcon_e2b6ef4c',
  errorIcon: 'errorIcon_e2b6ef4c',
  openLink: 'openLink_e2b6ef4c',
  modalCheckbox: 'modalCheckbox_e2b6ef4c'
};

export default styles;
/* tslint:enable */